#БУ-3П

[UPP.Name]
2 = "Диаметр бандажа первой колёсной пары"
3 = "Диаметр бандажа второй колёсной пары"
4 = "Наличие МПМЭ"
5 = "Тип локомотива или электросекции"
6 = "Номер локомотива или электросекции"
7 = "Число зубьев датчика угла поворота"
8 = "Верхний предел шкалы"
9 = "Дискретность регистрации пути"
10 = "Дискретность регистрации скорости"
11 = "Наличие БР-2М"
12 = "Верхний предел измерения давления в ТЦ"
13 = "Признак наличия блока контроля"
14 = "Уставка скорости V(ж)"
15 = "Уставка скорости V(кж)"
16 = "Уставка скорости V(упр)"
17 = "Признак одной или двух кабин или МВПС"
18 = "Код варианта системы АЛС"
19 = "Признак наличия БУС"
20 = "Кол-во метров для гребнесмазки"
21 = "Наличие комплекса КВАРТА"
22 = "Дискретность регистрации топлива"
#25 = "Количество дополнительных параметров"
#26 = "Количество знаков табельного номера"

[UPP.Value]
2 = "1350"
3 = "1350"
4 = "1"
5 = "111"
6 = "1"
7 = "42"
8 = "150"
9 = "100"
10 = "1.0"
11 = "0"
12 = "16"
13 = "0"
14 = "45"
15 = "30"
16 = "10"
17 = "1"
18 = "10"
19 = "0"
20 = "15"
21 = "0"
22 = "10"
#25 = "0"
#26 = "4"

[UPP.Hint]
2 = "Диапазон значений [600 - 1350]"
3 = "Диапазон значений [600 - 1350]"
4 = "Возможные значения [0, 1]"
5 = "Диапазон значений [111 - 999]"
6 = "Диапазон значений [1 - 9999]"
7 = "Диапазон значений [20 - 300]"
8 = "Возможные значения [50, 75, 100, 150]"
9 = "Возможные значения [20, 50, 100]"
10 = "Возможные значения [0.5, 1, 2]"
11 = "Возможные значения [0, 1]"
12 = "Диапазон значений [10 - 25]"
13 = "Возможные значения [0, 1]"
14 = "Диапазон значений [0 - 150]"
15 = "Диапазон значений [0 - 150]"
16 = "Диапазон значений [0 - 150]"
17 = "Возможные значения [1, 2, 3]"
18 = "Возможные значения [0, 1, 4, 5, 8, 9, 2, 10, 16, 24, 25, 32, 64]"
19 = "Возможные значения [0, 1]"
20 = "Диапазон значений [15 - 200]"
21 = "Возможные значения [0, 1, 2, 3]"
22 = "Диапазон значений [10 - 255]"
#25 = "Диапазон значений [0 - 4]"
#26 = "Диапазон значений [4 - 8]"
