#БУ-4

[UPP.Name]
2 = "Диаметр бандажа первой колёсной пары"
3 = "Диаметр бандажа второй колёсной пары"
5 = "Тип локомотива"
6 = "Номер локомотива"
7 = "Число зубьев ДУП"
8 = "Предел шкалы"
14 = "Уставка скорости V(ж)"
15 = "Уставка скорости V(кж)"
16 = "Уставка скорости V(упр)"
18 = "Тип АЛС"
21 = "Количество баков"
22 = "Дискретность регистрации топлива"
40 = "Количество ДУП"
41 = "Количество ДД"
46 = "Наличие плотномера (КВАРТА)"

[UPP.Value]
2 = "1350"
3 = "1350"
5 = "120"
6 = "1234"
7 = "42"
8 = "75"
14 = "40"
15 = "60"
16 = "30"
18 = "1"
21 = "1"
22 = "10"
40 = "2"
41 = "2"
46 = "0"

[UPP.Hint]
2 = "Диапазон значений [600 - 1350]"
3 = "Диапазон значений [600 - 1350]"
5 = "Диапазон значений [111 - 999]"
6 = "Диапазон значений [1 - 9999]"
7 = "Диапазон значений [20 - 300]"
8 = "Возможные значения [50, 75, 100, 150]"
14 = "Диапазон значений [0 - 150]"
15 = "Диапазон значений [0 - 150]"
16 = "Диапазон значений [0 - 150]"
18 = "Возможные значения [0, 1, 2, 4, 5, 8, 9, 10, 16, 24, 25, 32, 64]"
21 = "Возможные значения [0, 1, 2, 3]"
22 = "Диапазон значений [10 - 255]"
40 = "Возможные значения [1, 2]"
41 = "Возможные значения [1, 2]"
46 = "Возможные значения [0, 1]"
