[Errors.Description]
000 = "Отсутствие неисправностей"
100 = "Отсутствует связь с сопроцессором"
111 = "Значение скорости по 1 каналу превосходит предел шкалы на 20 %"
121 = "Значение скорости по 2 каналу превосходит предел шкалы на 20 %"
114 = "Измеренное значение скорости по каналу 1 равно 0, а по 2 каналу превосходит 20 км/ч"
124 = "Измеренное значение скорости по каналу 2 равно 0, а по 1 каналу превосходит 20 км/ч"
131 = "Измеренное значение давления в тормозной магистрали равно или превосходит 10 кгс/см2"
132 = "Результат тестового измерения давления по контрольному каналу при начальном тестировании оказался вне заданного диапазона"
133 = "Измеренное значение давления в тормозном цилиндре равно или превосходит предел, заданный в РПЗУ"
135 = "Измеренное значение давления в канале 3 превосходит 10 кгс/см2"
141 = "Направление движения по двум каналам различно при скорости, превышающей 5 км/ч"
142 = "Направление движения изменилось при скорости, превышающей 5 км/ч"
151 = "Горят два или более огней ЛС"
152 = "Ключ «ЭПК» выключен, но горят огни ЛС"
161 = "Принятый в разрядах позиций крана 395 код не совпадает ни с одним из допустимых кодов"
162 = "При положении крана 395, отличном от положения перекрыши, принято наличие питания на клемме «П» блока управления ЭПТ"
171 = "Соответствие между кодом, принятым с ИФ, и показанием ЛС отсутствует более 7 с подряд (при красном и белом огнях не контролируется)"
172 = "Непрерывные сбои кода с ИФ в течение более 7 с"
200 = "Нет связи с модулем реле"
201 = "Принятый сигнал срабатывания реле уставок не соответствует выданному на них коду (реле 1)"
202 = "Принятый сигнал срабатывания реле уставок не соответствует выданному на них коду (реле 2)"
203 = "Принятый сигнал срабатывания реле уставок не соответствует выданному на них коду (реле 3)"
204 = "Принятый сигнал срабатывания реле уставок не соответствует выданному на них коду (реле 4)"
221 = "Принятый сигнал срабатывания реле уставок при проверке на включение во время начального тестирования не соответствует выданному на них коду (реле 1)"
222 = "Принятый сигнал срабатывания реле уставок при проверке на включение во время начального тестирования не соответствует выданному на них коду (реле 2)"
223 = "Принятый сигнал срабатывания реле уставок при проверке на включение во время начального тестирования не соответствует выданному на них коду (реле 3)"
224 = "Принятый сигнал срабатывания реле уставок при проверке на включение во время начального тестирования не соответствует выданному на них коду (реле 4)"
241 = "Принятый сигнал срабатывания реле уставок при проверке на выключение во время начального тестирования не соответствует выданному на них коду (реле 1)"
242 = "Принятый сигнал срабатывания реле уставок при проверке на выключение во время начального тестирования не соответствует выданному на них коду (реле 2)"
243 = "Принятый сигнал срабатывания реле уставок при проверке на выключение во время начального тестирования не соответствует выданному на них коду (реле 3)"
244 = "Принятый сигнал срабатывания реле уставок при проверке на выключение во время начального тестирования не соответствует выданному на них коду (реле 4)"
250 = "Отсутствует блок контроля"
260 = "Неисправно реле питания ЭПК"
261 = "Неисправно реле РБ"
262 = "Неисправно реле ЭМВ"
300 = "Отсутствует связь с БУС"
367 = "Выход давления масла ДГУ за нижний предел" #bu4
378 = "Выход температуры воды ДГУ за верхний предел" #bu4
382 = "Неисправность КРПД первой секции"
385 = "Неисправность КРПД второй секции"
388 = "Неисправность КРПД третьей секции"
391 = "Неисправность КРПД четвертой секции"
383 = "Неисправность ДГУ первой секции"
386 = "Неисправность ДГУ второй секции"
389 = "Неисправность ДГУ третьей секции"
392 = "Неисправность ДГУ четвертой секции"
384 = "Критическая ошибка ДГУ первой секции"
387 = "Критическая ошибка ДГУ второй секции"
390 = "Критическая ошибка ДГУ третьей секции"
393 = "Критическая ошибка ДГУ четвертой секции"
400 = "Отсутствует связь с БИ"
403 = "Отсутствует связь со стрелочным индикатором"
404 = "Сбой стрелочного индикатора"
450 = "Сбои БИ: отсутствует связь с клавиатурой"
451 = "Сбои БИ: отсутствует связь с основным цифровым индикатором"
452 = "Сбои БИ: отсутствует связь с дополнительным цифровым индикатором"
453 = "Сбои БИ: отсутствует связь со стрелочным индикатором"
454 = "Сбои БИ: сбой стрелочного индикатора"
550 = "Нет свяэи с контроллером измерений уровня топлива (топливный бак бак №1)"
560 = "Нет свяэи с контроллером измерений уровня топлива (топливный бак бак №2)"
570 = "Нет свяэи с контроллером измерений уровня топлива (топливный бак бак №3)"
580 = "Нет свяэи с контроллером измерений уровня топлива (топливный бак бак №4)"
551 = "Не отвечает датчик температуры №1 (топливный бак бак №1)"
561 = "Не отвечает датчик температуры №1 (топливный бак бак №2)"
571 = "Не отвечает датчик температуры №1 (топливный бак бак №3)"
581 = "Не отвечает датчик температуры №1 (топливный бак бак №4)"
552 = "Не отвечает датчик температуры №2 (топливный бак бак №1)"
562 = "Не отвечает датчик температуры №2 (топливный бак бак №2)"
572 = "Не отвечает датчик температуры №2 (топливный бак бак №3)"
582 = "Не отвечает датчик температуры №2 (топливный бак бак №4)"
553 = "Не отвечает датчик уровня топлива №1 (топливный бак бак №1)"
563 = "Не отвечает датчик уровня топлива №1 (топливный бак бак №2)"
573 = "Не отвечает датчик уровня топлива №1 (топливный бак бак №3)"
583 = "Не отвечает датчик уровня топлива №1 (топливный бак бак №4)"
554 = "Не отвечает датчик уровня топлива №2 (топливный бак бак №1)"
564 = "Не отвечает датчик уровня топлива №2 (топливный бак бак №2)"
574 = "Не отвечает датчик уровня топлива №2 (топливный бак бак №3)"
584 = "Не отвечает датчик уровня топлива №2 (топливный бак бак №4)"
555 = "Не отвечает или неисправен датчик плотности (топливный бак бак №1)"
565 = "Не отвечает или неисправен датчик плотности (топливный бак бак №2)"
575 = "Не отвечает или неисправен датчик плотности (топливный бак бак №3)"
585 = "Не отвечает или неисправен датчик плотности (топливный бак бак №4)"
556 = "КВАРТА передал не корректные значения начальной плотности и температуры"
557 = "Не удалось записать начальные значения плотности и температуры"
600 = "Отсутствует связь с МПМЭ (нет МПМЭ)"
608 = "МПМЭ заполнен более чем на 90%"
609 = "МПМЭ переполнен (заполнен на 100%)"
700 = "Сбой информации в РПЗУ"
701 = "Расхождение диаметров бандажа колесных пар более 20 мм"
702 = "Некорректное значение параметра в РПЗУ" #// УПП
703 = "Некорректное значение параметра в РПЗУ"
704 = "Некорректное значение параметра в РПЗУ"
705 = "Некорректное значение параметра в РПЗУ"
706 = "Некорректное значение параметра в РПЗУ"
707 = "Некорректное значение параметра в РПЗУ"
708 = "Некорректное значение параметра в РПЗУ"
709 = "Некорректное значение параметра в РПЗУ"
710 = "Некорректное значение параметра в РПЗУ"
711 = "Некорректное значение параметра в РПЗУ"
712 = "Некорректное значение параметра в РПЗУ"
713 = "Некорректное значение параметра в РПЗУ"
714 = "Некорректное значение параметра в РПЗУ"
715 = "Некорректное значение параметра в РПЗУ"
716 = "Некорректное значение параметра в РПЗУ"
717 = "Некорректное значение параметра в РПЗУ"
718 = "Некорректное значение параметра в РПЗУ"
719 = "Некорректное значение параметра в РПЗУ"
720 = "Некорректное значение параметра в РПЗУ"
800 = "Отсутствует связь с РПЗУ (ошибка чтения/записи)"
851 = "Сбой основного индикатора"
852 = "Сбой дополнительного индикатора"
853 = "Отсутствует связь со стрелочным индикатором"
854 = "Сбой стрелочного индикатора"
855 = "Сбой клавиатуры"
857 = "Отсутствует связь с часами реального времени"
858 = "Сбой двоичных входов"
859 = "Сбой АЦП"
860 = "Сбой по CAN-каналу"
# 900 - 949 Внутренние ошибки исполнения 
# 100 700-720 800 не возможна поездка
